name: DNN
channels:
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - pip:
    - torchvision
    - torch
    - scikit-image
    - opencv-python